### ISSUE TITLE
Error calling application

### ISSUE THREAD

**Issue by Romathonat** [erocci/erocci#71] opened 2016-07-05 13:56 UTC
Error calling query interface /-/ (or any other path) using default sys.config (./start.sh) :

```
Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.220.0> exit with reason: 
{cowboy_handler,
  [{class,error},{reason,badarg},{mfa,{erocci_http_handler,to,2}},
   {stacktrace,
      [{jsx_parser,value,4,
         [{file,"src/jsx_parser.erl"},{line,152}]},
          {erocci_http_handler,to,2,
        [{file,"src/erocci_http_handler.erl"},{line,180}]},{cowboy_rest,call,3,
        [{file,"src/cowboy_rest.erl"},{line,1121}]},{cowboy_rest,set_resp_body,2,
        [{file,"src/cowboy_rest.erl"},{line,1003}]},{cowboy_protocol,execute,4,
        [{file,"src/cowboy_protocol.erl"},{line,470}]}]},
          {req,[{socket,#Port<0.6533>},{transport,ranch_tcp},{connection,keepalive},
          {pid,<0.220.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},34159}},
         {host,<<"localhost">>},{host_info,undefined},{port,8080},{path,<<"/-/">>},
         {path_info,undefined},{qs,<<>>},{bindings,[]},{headers,[{<<"host">>,<<"localhost:8080">>},
         {<<"user-agent">>,<<"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 
   Firefox/47.0">>},{<<"accept">>,<<"application/json">>},{<<"accept-language">>,
           <<"en-US,en;q=0.5">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"referer">>, 
           <<"http://localhost:8080/api-docs/index.html">>},{<<"connection">>,<<"keep-alive">>}]},
          {meta,[{media_type,{<<"application">>,<<"json">>,[]}},{charset,undefined}]},
          {body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,true},
          {resp_state,waiting},{resp_headers,[{<<"vary">>,[<<"accept">>]},{<<"content-type">>,
         [<<"application">>,<<"/">>,<<"json">>,<<>>]},{<<"server">>,"erocci OCCI/1.2"}]},
          {resp_body,<<>>},{onresponse,undefined}]},
        {state,{ok,[{kind,{<<"http://schemas.ogf.org/occi/core#">>,<<"link">>},
         #{actions => #{},attributes => #{<<"occi.core.source">> => #{category => 
              {<<"http://schemas.ogf.org/occi/core#">>,<<"link">>},default => undefined,
           description => <<>>,mutable => true,name => <<"occi.core.source">>,pattern => 
           undefined,required => true,title => <<"The Resource instance this Link instance originates 
          from">>,type => resource},<<"occi.core.source.kind">> => #{category => 
      {<<"http://schemas.ogf.org/occi/core#">>,<<"link">>},default => undefined, 
        description => <<>>,mutable => true,name => <<"occi.core.source.kind">>,
        pattern => undefined,required => false,title => <<"The Kind of source">>,type => kind},
        <<"occi.core.target">> => #{category => {<<"http://schemas.ogf.org/occi/core#">>,
        <<"link">>},default => undefined,description => <<>>,mutable => true,name => 
       <<"occi.core.target">>,pattern => undefined,required => true,title => <<"The unique 
        identifier of an Object this Link instance points to">>,type => uri},<<"occi.core.target.kind">>
        => #{category => {<<"http://schemas.ogf.org/occi/core#">>,<<"link">>},default => 
        undefined,description => <<>>,mutable => true,name => <<"occi.core.target.kind">>,
       pattern => undefined,required => false,title => <<"The Kind of target, if applicable">>,
       type => kind}},location => <<"/categories/link">>,parents => 
      [{<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>}],title => <<"Core Link">>}},
      {kind,{<<"http://example.org/occi/test#">>,<<"user">>},#{actions => #{},
      attributes => #{<<"blog.user.email">> => #{category => {<<"http://example.org/occi/test#">>,
       <<"user">>},default => undefined,description => <<>>,mutable => true,name => 
      <<"blog.user.email">>,pattern => undefined,required => false,title => <<"User email">>,
      type => string},<<"blog.user.name">> => #{category => {<<"http://example.org/occi/test#">>,
     <<"user">>},default => undefined,description => <<>>,mutable => true,name => 
     <<"blog.user.name">>,pattern => undefined,required => true,title => <<"User name">>,
     type => string},<<"blog.user.role">> => #{category => {<<"http://example.org/occi/test#">>,
    <<"user">>},default => undefined,description => <<>>,mutable => true,name => 
    <<"blog.user.role">>,pattern => undefined,required => false,title => <<"User role">>,type => 
    string}},location => <<"/categories/user">>,parents => [{<<"http://schemas.ogf.org/occi/core#">>,
    <<"resource">>},{<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>}],title => <<"Blog user">>}},
    {kind,{<<"http://example.org/occi/test#">>,<<"entry">>},#{actions => #{},attributes => 
    #{<<"blog.entry.content">> => #{category => {<<"http://example.org/occi/test#">>,
    <<"entry">>},default => undefined,description => <<>>,mutable => true,name => 
    <<"blog.entry.content">>,pattern => undefined,required => true,title => <<"Entry content">>,
    type => string},<<"blog.entry.date">> => #{category => {<<"http://example.org/occi/test#">>,
    <<"entry">>},default => undefined,description => <<>>,mutable => true,name => 
    <<"blog.entry.date">>,pattern => undefined,required => false,title => <<"Creation date">>,
    type => string},<<"blog.entry.title">> => #{category => {<<"http://example.org/occi/test#">>,
    <<"entry">>},default => undefined,description => <<>>,mutable => true,name => 
    <<"blog.entry.title">>,pattern => undefined,required => true,title => <<"Blog entry title">>,
    type => string}},location => <<"/categories/entry">>,parents => 
    [{<<"http://schemas.ogf.org/occi/core#">>,<<"resource">>},
    {<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>}],title => <<"entry">>}},
    {kind,{<<"http://example.org/occi/test#">>,<<"author">>},#{actions => #{},attributes => #{},
    location => <<"/categories/author">>,parents => [{<<"http://schemas.ogf.org/occi/core#">>,
   <<"link">>},{<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>}],title => <<"Author">>}},
   {kind,{<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>},#{actions => #{},attributes => 
   #{<<"occi.core.id">> => #{category => {<<"http://schemas.ogf.org/occi/core#">>,
   <<"entity">>},default => undefined,description => <<>>,mutable => true,name => 
    <<"occi.core.id">>,pattern => undefined,required => false,title => <<"Id">>,type => string},
    <<"occi.core.title">> => #{category => {<<"http://schemas.ogf.org/occi/core#">>,
    <<"entity">>},default => undefined,description => <<>>,mutable => true,name => 
    <<"occi.core.title">>,pattern => undefined,required => false,title => <<"Display name">>,
    type => string}},location => <<"/categories/entity">>,parents => [],title => <<"Core Entity">>}},
    {kind,{<<"http://schemas.ogf.org/occi/core#">>,<<"resource">>},#{actions => #{},
    attributes => #{<<"occi.core.summary">> => #{category => 
   {<<"http://schemas.ogf.org/occi/core#">>,<<"resource">>},default => undefined,
    description => <<>>,mutable => true,name => <<"occi.core.summary">>,
   pattern => undefined,required => false,title => <<"Summarising description">>,
   type => string}},location => <<"/categories/resource">>,parents =>
    [{<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>}],title => <<"Core Resource">>}},
    {kind,{<<"http://example.org/occi/test#">>,<<"blog">>},#{actions => #{},
   attributes => #{<<"example.blog.title">> => #{category => 
   {<<"http://example.org/occi/test#">>,<<"blog">>},default => undefined,description => <<>>,
   mutable => true,name => <<"example.blog.title">>,pattern => undefined,required => true,
   title => <<"Blog title">>,type => string}},location => <<"/categories/blog">>,
   parents => [{<<"http://schemas.ogf.org/occi/core#">>,<<"resource">>},
   {<<"http://schemas.ogf.org/occi/core#">>,<<"entity">>}],title => <<"A Blog">>}}],undefined}}]}
```

I tried to find the xml file describing api (occi.xml I guess), but it not very clear to me where to find it (it this the one on tools/docker/ ? Or maybe one of those in deps/ ?).
Moreover, it would be nice to update the documention. The one on [http://erocci.ow2.org/#/getstarted](http://erocci.ow2.org/#/getstarted) seems outdated, and the one on the github too. For me, there is no file to make a ./bootstrap, and no apps/erocci/priv/configs/ folder. More explanations would be really appreciated.
Thanks in advance !

**Comment by jeanparpaillon** [comment] 2016-07-06 08:30
Regarding error, can you post the full request and eventually every information needed to reproduce ?

Regarding the documentation: help needed :) See https://github.com/erocci/erocci-www 
and 
https://github.com/erocci/erocci/issues/72

**Comment by Romathonat** [comment] 2016-07-06 08:57
Alright Marc helped me solve it :)
The problem was that I used the website erroci to deploy erocci, and the given command used to install dependencies was not up to date, so I had not the good version of Erlang. When recompiling the project, with the good version of Erlang, the old deps/ folder stayed, and that is why all was broken. You just have to make a rm -rf /dist, and then a make, and it works like a charm.
Could you please just tell me where to find the xml which configure the server ? Thanks.
Moreover I will improve the documentation if you want.

**Comment by jeanparpaillon** [comment] 2016-07-06 09:05
Regarding the place of occi.xml, in file `config/sys.config`, you can replace `{priv_dir, "path.xml"}` with `"/absolute/path/to/your/xml"`.

> Moreover I will improve the documentation if you want.

I had to read the erocci_backend_mnesia code to answer you :(
Indeed, erocci_backend_mnesia can be specified the OCCI schema the following ways:
```erlang
{schema, {priv_dir, "path/to.xml"}}
```
-> read schema from `erocci_backend_mensia/priv/path/to.xml`

```erlang
{schema, "/absolute/path/to.xml"}
```
-> read schema from absolute path

```erlang
{schema, {extension, "http://example.org/occi/schema#"}}
```
-> read schema from well know schema repository (actually only http://github.com/occiware/occi-schemas)

GREAT :)

**Comment by jeanparpaillon** [comment] 2016-07-06 09:05
I propose you close this bug as we can consider the problem is the doc ?

**Comment by Romathonat** [comment] 2016-07-07 09:00
Did those commands work for you?
When I make a simple 
```
[{schema, {priv_dir, "occi-infrastruture.xml"}}],
```
it does not work.

Error log : 
```
{"init terminating in do_boot",{{badmatch,{error,{erocci_core,{{enoent,{child,undefined,root,{erocci_backend,start_link,[{backend,root,erocci_backend_mnesia,[{schema,{priv_dir,"occi-infrastruture.xml"}}],[],<<>>,0}]},permanent,5000,worker,[erocci_backend,erocci_backend_mnesia]}},{erocci_core,start_phase,[backends,normal,[]]}}}}},[{erocci,start,0,[{file,"src/erocci.erl"},{line,28}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
```

**Comment by jeanparpaillon** [comment] 2016-07-13 15:44
Please open another bug when this is another error.

The error is 'enoent': file is not found. `priv_dir` is relative to erocci_backend_mnesia application.
See http://erlang.org/doc/man/code.html#priv_dir-1

**Closed by jeanparpaillon** 2016-07-13 15:44 UTC

**Comment by Romathonat** [comment] 2016-07-18 09:49
I figured out the problem [here](https://github.com/occiware/ecore/issues/138)

**Comment by jeanparpaillon** [comment] 2016-07-18 09:50
Great
